import { type RouteConfig, route } from "@react-router/dev/routes";
export default [
  route("/app/rewards", "./routes/app.rewards.jsx"),
  route("/api/redeem", "./routes/api.redeem.ts"),
  route("/api/balance", "./routes/api.balance.ts"),
  route("/api/wallet", "./routes/api.wallet.ts"),
  route("/api/proxy/wallet", "./routes/api.proxy.wallet.ts"),
  route("/api/order", "./routes/api.order.ts"),
  route("/api/referral/generate", "./routes/api.referral.generate.ts"),
  route("/api/referral/apply", "./routes/api.referral.apply.ts"),
  route("/webhooks/orders/create", "./routes/webhooks.orders.create.ts"),
  route("/webhooks/app/uninstalled", "./routes/webhooks.app.uninstalled.ts"),
  route("/webhooks/orders/paid", "./routes/webhooks.orders.paid.ts"),
  route("/api/subscription", "./routes/api.subscription.ts"),
  route("/api/subscription/manage", "./routes/api.subscription.manage.ts"),
  route("/api/points/expire", "./routes/api.points.expire.ts"),
  route("/api/points/transfer", "./routes/api.points.transfer.ts"),
  route("/api/points/checkout", "./routes/api.points.checkout.ts"),
  route("/webhooks/subscriptions/create", "./routes/webhooks.subscriptions.create.ts"),
  route("/webhooks/subscriptions/billing", "./routes/webhooks.subscriptions.billing.ts"),
  route("/api/webhooks/register", "./routes/api.webhooks.register.ts"),
  route("/api/admin/test", "./routes/api.admin.test.ts"),
  route("/api/cron/update-months", "./routes/api.cron.update-months.ts"),
  route("/api/admin/add-points", "./routes/api.admin.add-points.ts"),
] satisfies RouteConfig;
